/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Filme;

/**
 *
 * @author Jao
 */
public class TelaRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();

        FilmeController filmeController = new FilmeController();
        ArrayList<Filme> listaDeFilmes = filmeController.listar();

        if(listaDeFilmes.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhum filme cadastrado para exibir no relatório.", "Relatório Vaio",JOptionPane.INFORMATION_MESSAGE);
        } else{
            StringBuilder relatorio = new StringBuilder();
            relatorio.append("--- RELATÓRIO DE FILMES CADASTRADOS ---\n\n");
            
            for(Filme filme: listaDeFilmes){
                relatorio.append("ID: ").append(filme.getId()).append("\n");
                relatorio.append("Título: ").append(filme.getTitulo()).append("\n");
                relatorio.append("Gênero: ").append(filme.getGenero()).append("\n");
                relatorio.append("Diretor: ").append(filme.getDiretor()).append("\n");
                relatorio.append("Ano: ").append(filme.getAno()).append("\n");
                relatorio.append("--------------------------------------------\n");
            }
            txtAreaRelatorio.setText(relatorio.toString());
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRelatorio = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        setTitle("Relatório");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/filme.png"))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        txtAreaRelatorio.setEditable(false);
        txtAreaRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaRelatorio.setColumns(20);
        txtAreaRelatorio.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtAreaRelatorio.setRows(5);
        txtAreaRelatorio.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(txtAreaRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaRelatorio;
    // End of variables declaration//GEN-END:variables
}
