package view;

import controller.AvaliacaoController;
import controller.FilmeController;
import controller.UsuarioController;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.Avaliacao;
import model.Filme;

/**
 *
 * @author Jao
 * @author lais.v
 */
public class TelaAvaliacaoFilme extends javax.swing.JInternalFrame {

    private Avaliacao avaliacao;
    private AvaliacaoController avaliacaoController;
    private ArrayList<Filme> listaFilmes;

    public TelaAvaliacaoFilme() {
        initComponents();
        avaliacaoController = new AvaliacaoController();
        carregarTabelaAvaliacao();
        carregarTitulosFilmes();
        limparCampos();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAvaliacao = new javax.swing.JTable();
        remover_Button = new javax.swing.JButton();
        editar_Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        username_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filme_ComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nota_Txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentario_TextArea = new javax.swing.JTextArea();
        salvar_Button = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Avaliar Filme");

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 251));
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tabelaAvaliacao.setBackground(new java.awt.Color(255, 255, 251));
        tabelaAvaliacao.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tabelaAvaliacao.setForeground(new java.awt.Color(0, 102, 153));
        tabelaAvaliacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Filme", "Nota", "Comentário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaAvaliacao.setGridColor(new java.awt.Color(255, 255, 251));
        tabelaAvaliacao.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tabelaAvaliacao.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaAvaliacao.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaAvaliacao.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaAvaliacao.setShowGrid(true);
        jScrollPane2.setViewportView(tabelaAvaliacao);

        remover_Button.setBackground(new java.awt.Color(255, 255, 251));
        remover_Button.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        remover_Button.setForeground(new java.awt.Color(0, 102, 153));
        remover_Button.setText("Remover");
        remover_Button.setBorder(null);
        remover_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_ButtonActionPerformed(evt);
            }
        });

        editar_Button.setBackground(new java.awt.Color(255, 255, 251));
        editar_Button.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        editar_Button.setForeground(new java.awt.Color(0, 102, 153));
        editar_Button.setText("Salvar edição");
        editar_Button.setBorder(null);
        editar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(remover_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remover_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de Avaliações", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        username_Panel.setBackground(new java.awt.Color(255, 255, 255));
        username_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        username_Panel.setForeground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Selecione o filme: ");

        filme_ComboBox.setBackground(new java.awt.Color(255, 255, 251));
        filme_ComboBox.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        filme_ComboBox.setForeground(new java.awt.Color(51, 51, 51));
        filme_ComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Nota (1-10):");

        nota_Txt.setBackground(new java.awt.Color(255, 255, 251));
        nota_Txt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nota_Txt.setForeground(new java.awt.Color(51, 51, 51));
        nota_Txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 102, 153)));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Comentário:");

        comentario_TextArea.setBackground(new java.awt.Color(255, 255, 251));
        comentario_TextArea.setColumns(20);
        comentario_TextArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        comentario_TextArea.setForeground(new java.awt.Color(51, 51, 51));
        comentario_TextArea.setRows(5);
        comentario_TextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jScrollPane1.setViewportView(comentario_TextArea);

        javax.swing.GroupLayout username_PanelLayout = new javax.swing.GroupLayout(username_Panel);
        username_Panel.setLayout(username_PanelLayout);
        username_PanelLayout.setHorizontalGroup(
            username_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(username_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(username_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(username_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filme_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(username_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nota_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 66, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        username_PanelLayout.setVerticalGroup(
            username_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(username_PanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(username_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filme_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(username_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nota_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        salvar_Button.setBackground(new java.awt.Color(255, 255, 251));
        salvar_Button.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        salvar_Button.setForeground(new java.awt.Color(51, 51, 51));
        salvar_Button.setText("Salvar");
        salvar_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salvar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(username_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salvar_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(username_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adicionar Avaliaçao", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void carregarTitulosFilmes() {
        FilmeController filmeController = new FilmeController();
        listaFilmes = filmeController.listar();

        filme_ComboBox.removeAll();
        for (Filme f : listaFilmes) {
            filme_ComboBox.addItem(f.getTitulo());
        }
    }

    public void carregarTabelaAvaliacao() {
        DefaultTableModel model = (DefaultTableModel) tabelaAvaliacao.getModel();
        model.setRowCount(0);

        FilmeController filmeController = new FilmeController();
        ArrayList<Avaliacao> avaliacaoList = avaliacaoController.listarPorUsuario(TelaLogin.idLogado);

        TableColumn filmeColumn = tabelaAvaliacao.getColumnModel().getColumn(0);
        filmeColumn.setCellEditor(new DefaultCellEditor(filme_ComboBox));

        for (Avaliacao a : avaliacaoList) {
            String tituloFilme = filmeController.buscarPorId(a.getFilmeId()).getTitulo();
            model.addRow(new Object[]{tituloFilme, a.getNota(), a.getComentario()});
        }
    }

    private void salvar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_ButtonActionPerformed
        String notaStr = nota_Txt.getText().replaceAll(",", ".");
        int nota;
        if (notaStr.isBlank() || notaStr.isEmpty()) {
            nota = -1;
        } else {
            try {
                nota = Integer.parseInt(notaStr);
            } catch (NumberFormatException e) {
                double notaQuebrada = Double.parseDouble(notaStr);
                nota = (int) Math.round(notaQuebrada);
            }
        }

        avaliacao = new Avaliacao(TelaLogin.idLogado, filmeId(), nota, comentario_TextArea.getText());
        avaliacaoController.cadastrar(avaliacao);
        carregarTabelaAvaliacao();
        limparCampos();
    }//GEN-LAST:event_salvar_ButtonActionPerformed

    private void editar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_ButtonActionPerformed
        int linha = tabelaAvaliacao.getSelectedRow();

        if (linha >= 0) {
            FilmeController filmeController = new FilmeController();
            String tituloFilme = tabelaAvaliacao.getValueAt(linha, 0).toString();
            int filmeId = filmeController.buscarPorTitulo(tituloFilme).getId();

            String notaStr = tabelaAvaliacao.getValueAt(linha, 1).toString();
            int nota;

            try {
                nota = Integer.parseInt(notaStr);
            } catch (NumberFormatException ex) {
                try {
                    double notaQuebrada = Double.parseDouble(notaStr);
                    nota = (int) Math.round(notaQuebrada);
                    JOptionPane.showMessageDialog(null, "Nota arredondada para " + nota, "Aviso", JOptionPane.WARNING_MESSAGE);
                } catch (NumberFormatException e2) {
                    JOptionPane.showMessageDialog(null, "A nota deve ser um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            String comentario = tabelaAvaliacao.getValueAt(linha, 2).toString();

            Avaliacao nova = new Avaliacao(TelaLogin.idLogado, filmeId, nota, comentario);
            avaliacaoController.editar(TelaLogin.idLogado, filmeId, nova);
            carregarTabelaAvaliacao();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma avaliação para editar.", "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_editar_ButtonActionPerformed

    private void remover_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_ButtonActionPerformed
        FilmeController filmeController = new FilmeController();
        int linha = tabelaAvaliacao.getSelectedRow();
        if (linha >= 0) {
            int filmeId = filmeController.buscarPorTitulo(tabelaAvaliacao.getValueAt(linha, 0).toString()).getId();

            avaliacaoController.remover(TelaLogin.idLogado, filmeId);
            carregarTabelaAvaliacao();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma avaliação para remover.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_remover_ButtonActionPerformed

    private int filmeId() {
        for (Filme f : listaFilmes) {
            if (f.getTitulo().equalsIgnoreCase(filme_ComboBox.getSelectedItem().toString())) {
                return f.getId();
            }
        }
        return -1;
    }

    private void limparCampos() {
        nota_Txt.setText(null);
        comentario_TextArea.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comentario_TextArea;
    private javax.swing.JButton editar_Button;
    private javax.swing.JComboBox<String> filme_ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nota_Txt;
    private javax.swing.JButton remover_Button;
    private javax.swing.JButton salvar_Button;
    private javax.swing.JTable tabelaAvaliacao;
    private javax.swing.JPanel username_Panel;
    // End of variables declaration//GEN-END:variables
}
